### ISSUE TITLE
`Nonce` is not used in Amber AS

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/trustee#151]
https://github.com/confidential-containers/kbs/blob/main/src/api/src/attestation/amber/mod.rs#L51

The `nonce` parameter is a crytical parameter in KBS RCAR protocol. See https://github.com/confidential-containers/kbs/blob/main/docs/kbs_attestation_protocol.md#challenge

It helps to avoid reply attack from the attestation-agent side.

Currently Amber attestation service does not check the nonce field, thus having some secure problems.

cc @Lu-Biao

**Comment by mythi** [comment]
I'm looking into this.
