### ISSUE TITLE
Attestation-Service: Should the SNP verifier claim set include more than REPORTED_TCB?

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/trustee#235]
On SEV_SNP microcode-only updates to a PSP might not be reflected in an snp report's `reported_tcb.microcode` field, but only in `current_tcb.microcode`. Currently we are only including the `reported_tcb.*` fields in the claim-set. To express a microcode only-update in a policy, we would want to include `current_tcb.*`.

cc @fitzthum 

Folks at AMD should confirm the above reasoning makes sense, I'm not entirely sure. cc @ryansavino @larrydewey

**Comment by fitzthum** [comment]
I am a little confused by this behavior. According to 56860

> ReportedTcb is initially set to the CurrentTcb. When SNP_CONFIG is invoked with a non-zero
> REPORTED_TCB parameter, ReportedTcb is set to the provided value. ReportedTcb is reset to
> CurrentTcb either on SNP_COMMIT or if SNP_CONIFG is provided a zero REPORTED_TCB.

Is this not true in the case of microcode-only updates?

**Comment by mkulke** [comment]
according to [this presentation](https://www.amd.com/content/dam/amd/en/documents/developer/lss-snp-attestation.pdf) (p11) `current_tcb` would indeed be merely "informational"

<img width="904" alt="image" src="https://github.com/confidential-containers/kbs/assets/273280/8bec1883-e27c-4907-ae1f-53e5d6677f01">

...

AFAIU `reported_tcb` is meant to cover a specific situation: Assume a given policy asserts `tcb.fw_version == 1.0`. Now the infra owner applies a patch on the system to bump the PSP firmware to `1.1`. The assertion in the policy would fail, potentially breaking things for the guest owner. Hence at guest creation the infra owner can opt to still report `tcb.fw_version: 1.0` at guest creation. until the guest owner adjust their policy accordingly.

That would reflect the situation in the initial comment. The infra-owner applied a microcode update, but the hypervisor chose to report an older TCB to the guest. In this sense everything works as designed.

Now, the guest owner might not be able to influence launch parameters of their specific virtual machine. In a public cloud `reported_tcb` might be configured globally to the fleet and be updated conservatively. In this case there's no way for the guest owner to write an attestation-service policy asserting TCB values larger than the reported one, even if the fleet has been patched. 🤔 

(rephrasing the issue title)

**Comment by mkulke** [comment]
related slack discussion about issues in the spec: https://cloud-native.slack.com/archives/C03K97S5JQL/p1695202432334559

**Comment by fitzthum** [comment]
I agree that this is the idea of the REPORTED_TCB. I am trying to understand if the behavior that you are seeing is the result of a bug or if the hypervisor is deliberately avoiding updating the REPORTED_TCB. While there is value in being conservative about the REPORTED_TCB, if there is a critical update that the user will expect to verify, I think the CSP should update the REPORTED_TCB to reflect the new version. Ofc this isn't really my decision to make. I wouldn't mind adding the extra fields to the claims map although I'm not sure that it's ideal for users to write policies that depend on the current TCB except in this particular case.

**Comment by fitzthum** [comment]
@mkulke do you remember what we concluded here? Can we close this?

**Comment by mkulke** [comment]
I don't remember the conclusion either (probably there was none) and I think there has been some change in behaviour since, so let's revive this once it pops up again.
