### ISSUE TITLE
KBS (protocol) enhancements to reportdata generation

### ISSUE THREAD

**Issue by mythi** [confidential-containers/trustee#242]
The original case was reported in #162 triggered by my work on #159 and a bit of #151 too. This issue is an RFC proposal based on ideas I've prepared with @Xynnn007 to get CoCo attesters to generate quotes/reportdata in a generic way so that they can be made consumable by different AS backends.

The source of the problem is: `hash(nonce || runtime data)` and how to keep the attester vs verifier in sync. Current CoCo setup uses `sha384` hash for all TEEs and the nonce is from the KBS session. This fails with Intel trust authority that expects `sha256` and `sha512` for SGX and TDX, respectively. IOW: CoCo attester generated evidence cannot be verified by Intel Trustauthority.

For this to work with non-CoCo attestation-services, two problems need to be sorted out:

1. it must be possible to seed `nonce` from the Attestation service
2. it must be possible to specify hash algorithm to be used by the attester.

This focuses on 2.

# Current RCAR handshake protocol

1. __Request__ from Client to Server
```json
{
    "version": "0.1.0",
    "tee": "$tee",
    "extra-params": {}
}
```

2. __Challenge__ from Server to Client: 
```json
{
    "nonce": "$nonce",
    "extra-params": {}
}
```

3. __Attestation__ from Client to Server
```json
{
    "tee-pubkey": "$pubkey",
    "tee-evidence": {}
}
```

4. __Response__ from Server to Client: 
```json
{
    "protected": "$jose_header",
    "encrypted_key": "$encrypted_key",
    "iv": "$iv",
    "ciphertext": "$ciphertext",
    "tag": "$tag"
}
```

# Suggested protocol changes

1. add an extra param "supported-hash-algorithms" to __Request__. This
helps the client to tell the server what hash algorithms are supported.

```json
{
    "version": "0.1.0",
    "tee": "$tee",
    "extra-params": {
        "supported-hash-algorithms": ["sha256", "sha384", "sha512"]
    }
}
```

2. add an extra param "selected-hash-algorithm" to __Challenge__. This
tells the hash algorithm that the server selects from the ones that
client supports.

```json
{
    "nonce": "$nonce",
    "extra-params": {
        "selected-hash-algorithm": "sha512"
    }
}
```

In this way, the KBS could select the hash algorithm depending on the TEE type and attestation service used.

For forward compatibility, the server should NOT response a __Challenge__ with
`selected-hash-algorithm` param when receiving a __Request__ without `supported-hash-algorithms` param. Instead, a __Challenge__ without `selected-hash-algorithm` should be sent. 

# Tasks

- [ ] #491 
- [ ] https://github.com/confidential-containers/guest-components/pull/712

**Comment by Xynnn007** [comment]
cc @sameo @slp @tylerfanelli @Lu-Biao

**Comment by Xynnn007** [comment]
btw, we need to raise a PR/issue in kbs-types repo to update the structure of both `Challenge` and `Request`, extending `extra_params` from `String` to `HashMap`

**Comment by pawelpros** [comment]
It's worth mentioning that - azure VTPM has limitation for get signed quote from TPM which in theory should be supported up to 64 bytes (Sha256/Sha385/Sha512) but in real case the limitation is **50 bytes** so Sha512 will not pass through

**Comment by mkulke** [comment]
> It's worth mentioning that - azure VTPM has limitation for get signed quote from TPM which in theory should be supported up to 64 bytes (Sha256/Sha385/Sha512) but in real case the limitation is **50 bytes** so Sha512 will not pass through

Note: that this is is a limitation in the tss API, since it uses a nonce buffer type that will be the size of the biggest hash algo available in a given TPM's PCR banks (which for azure vTPM is sha384) plus 2 additional header bytes (48 + 2). so, this limitation will most likely not be lifted anytime soon.
