### ISSUE TITLE
New name for the CoCo Attestation project

### ISSUE THREAD

**Issue by jiazhang0** [confidential-containers/trustee#250]
With the continuous improvement of the CoCo Attestation project, there is a growing demand to apply it in scenarios outside of CoCo, or to use only certain components (such as using Attestation-Agent to connect to other Attestation-Service). In fact, since the first day of designing the CoCo Attestation project, the project maintainers have anticipated this situation. Welcome everyone to submit their ideas here: https://doodle.com/meeting/participate/id/eEZ7g7ka.

However, before making the CoCo Attestation project more popular, we need to give it a better name to prevent "KBS" (Key Broker Service), which is a temporary name resulting from rebasing related repositories, from becoming the final name. The new name should reflect the inclusiveness and scalability of CoCo Attestation. The highest level of inclusiveness means that CoCo Attestation can even support attestation technologies beyond trusted execution environment attestation (such as build attestation, sbom attestation, platform attestation, etc.); Scalability has already begun to occur, for example, attestation needs to be integrated with traditional identity authentication and authorization, making the device identity for the TEE instance being the one of authentication and authorization factor.

An alternative name I propose is "AAA" (Attestation, Authentication, Authorization). I know that KBS in "AAA" also includes the functionality of storing sensitive information, but this is not the primary and unique capability of "AAA", so I prefer to highlight and emphasize the key features of CoCo Attestation in the new name.

@fitzthum @sameo @confidential-containers/kbs-maintainers @confidential-containers/attestation-agent-maintainers @confidential-containers/attestation-service-maintainers

**Comment by fitzthum** [comment]
I think you're right that we need a new name.

I like AAA. I have two potential concerns. First, it sounds fairly similar to AA, as in Attestation Agent. Second, I wonder if it sounds too generic. If the idea is for the KBS to catch on outside of CoCo, we might want a slightly more unique name. What do you think about A3? To me it sounds a bit cooler but that might be subjective.

**Comment by fitzthum** [comment]
What about attestation-hub or trust-center?

**Comment by kevinzs2048** [comment]
Just a thought, How about `pyramid`? For each surface of the pyramid, it is `A`

But one concern is we need to right description of the meaning :-)

**Comment by mythi** [comment]
> However, before making the CoCo Attestation project more popular, we need to give it a better name to prevent "KBS" (Key Broker Service), which is a temporary name resulting from rebasing related repositories, from becoming the final name.

The current state is because of an accidental push (that's what I was told). Before going into the repo naming discussion, we need to agree on the final structure. That topic was not finished properly.

**Comment by yangxile** [comment]
how about UAH(Universal Attestation Hub)?

**Comment by fitzthum** [comment]
What about AAAA or 4A? We just add Attestation onto the existing three As

**Comment by jepio** [comment]
Please something that is searchable (bing/google).

A proper name first, then an abbreviation of that. And the name should contain more than just generic terms.

**Comment by mkulke** [comment]
Why not use the descriptive and searchable term "attestation service"? It's namespaced by the CoCo project, so you could reference to it as "CoCo Attestation Service" to differentiate.

Arguably the scope of what's in the repo is larger than that, but the main substance is attestation.

**Comment by fitzthum** [comment]
[This](https://time.com/6551496/mickey-mouse-public-domain-steamboat-willie/) gives me an idea.

**Comment by dcmiddle** [comment]
> [This](https://time.com/6551496/mickey-mouse-public-domain-steamboat-willie/) gives me an idea.

Ok, I'll rename the repo to Steam-Boaty-McAttestation-Face

**Comment by wainersm** [comment]
> Just a thought, How about `pyramid`? For each surface of the pyramid, it is `A`
> 
> But one concern is we need to right description of the meaning :-)

I like names that aren't simple acronyms. :)

Stamp **seals** were used on ancient times to authenticate documents. Then I tried to derive some names from **seal**:
 - **Seaaal** (seal + triple A's)
 - **Ceaaal** (seaaal + s/S/C/) which for an acronym addicted could mean "ConfidEntial Attestation, Authentication, and Authorization Library"

**Comment by mkulke** [comment]
cereal 🥣

"confidentiality-enhanced remote attested ledger" or alternatively "confidentiality-enabling remote attestation library"

/s

**Comment by jialez0** [comment]
**OpenATA**   (Open ATtestation Architecture)

I think this name is professional and beautiful, which well describes the core goal and logic of this repository, that is, "a complete architecture level solution around Attestation technology". BTW, this name will help us to publicize and promote this project as an independent open source solution on different occasions.

In addition, up to now there are no other open source projects with this name, which is a good starting point.

**Comment by sameo** [comment]
Suggestions:

* AttestRA (as in Remote Attestation)
* Trustee (or Trusty) or Trust{ee,y}Hub or TrusteeLink

**Comment by fitzthum** [comment]
ProofRock - It's proof, it's a rock, and it's a reference to a [great poem](https://en.wikipedia.org/wiki/The_Love_Song_of_J._Alfred_Prufrock).

**Comment by jensfr** [comment]
CASPR: Confidential Attestation Service for Protected Resources

Casper is a friendly ghost, trusted and loved,  who often acts as an (invisible) protector of others. and he's fun ;-)

**Comment by Xynnn007** [comment]
Please see the poll discussion https://github.com/confidential-containers/kbs/discussions/302 :-)

**Comment by mythi** [comment]
> * Trustee (or Trusty) or Trust{ee,y}Hub or TrusteeLink

offtopic: I was wondering if we could find a Greek word (following Kubernetes etc) and looked for 'trust'. Looks like that's where Kata containers comes from (I did not know that!).

**Comment by mkulke** [comment]
> > * Trustee (or Trusty) or Trust{ee,y}Hub or TrusteeLink
> 
> offtopic: I was wondering if we could find a Greek word (following Kubernetes etc) and looked for 'trust'. Looks like that's where Kata containers comes from (I did not know that!).

IMO that's a great idea (albeit, admittedly the practice is a bit eurocentric):

There would be "Pistos" (πιστός) ~ faithful, trustworthy

And maybe "Fides" (Pistis), a roman-greek goddess of trust

**Comment by fitzthum** [comment]
We finished the poll [here](https://github.com/confidential-containers/kbs/discussions/302), The results show a tie between Trustee and CEREAL, but the last vote for CEREAL came in after we were supposed to have closed the poll (the start of the community meeting), and after we had actually announced the results. Of course we could do another poll with just those two options, but for the sake of everyone's sanity I think Trustee is the answer.

Now the question is how we actually go about renaming things

**Comment by Xynnn007** [comment]
@fitzthum Maybe we could raise this up in this week's meeting and rename with folks watching :P

**Comment by mythi** [comment]
> I think Trustee is the answer.

+1
