### ISSUE TITLE
Option to use  Versioned Loaded Endorsement Key (VLEK) for verifying SNP attestation report in AWS

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/trustee#286]
AWS SNP instances uses VLEK for verifying the attestation report.
Details are in the following reference doc - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snp-attestation.html

Any plans to support VLEK for SNP attestation ?

**Comment by wobito** [comment]
@bpradipt just wanted to ping you on this issue, I was able to get VLEK support working in AWS with #385 and just waiting for it to land in upstream code. Hope this helps solve your issue

**Comment by bpradipt** [comment]
> @bpradipt just wanted to ping you on this issue, I was able to get VLEK support working in AWS with #385 and just waiting for it to land in upstream code. Hope this helps solve your issue

@wobito I have been following your work on this. Great stuff and thanks for fixing the issue. I'll try the e2e scenario on AWS soon.
