### ISSUE TITLE
Q RVPS: Should reference values always be hashes?

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/trustee#369]
Currently we assume that reference values are always hashes of some format:

https://github.com/confidential-containers/trustee/blob/3d0b11d92e7aeea0d711beb4a6191c7a554f3cbf/attestation-service/rvps/src/reference_value.rs#L51-L71

How would we express expectations towards the claims for e.g. TCB versions? should those be coded into a policy?

**Comment by Xynnn007** [comment]
@mkulke RVPS now is still in prototype. About complex syntax about like numeric logic, set logic, etc are not supported by current data structure stored inside RVPS now as you showed. And if we want, I am afraid that the **ONLY** way we can use is the policy to support this for now.

Relative issue is https://github.com/confidential-containers/trustee/issues/350, one aim of whose is to replace the inner data structure inside RVPS to support more complex logic, like comparation of TCB version (numeric logic), etc.
