### ISSUE TITLE
Support for modular KMS components

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/trustee#37]
Now key management has a relatively mature industry implementation, it is required for KBS to support different KMSes as the backend to store keys and secrets. In this scenario, KBS plays a role of proxy. Maybe we should give a modular design to support different backends.

Here are some straightforward questions:
1. How to design the modularization?
2. How to let KBS know the accessed resource is from a KMS not stored in the KBS? (By the resource URI? How?)

**Comment by jialez0** [comment]
@Xynnn007 This is a preliminary design concept:

In the CoCo scenario, two keys need to be obtained from KBS:
1. The symmetric data-key used to decrypt the container image encryption key.
2. The public key used to verify the container image signature.

Considering that users may need to use KMS to manage the above keys, KBS needs to support docking KMS to obtain the above two keys.

To achieve this, we need to add two APIs in KBS:

```
/kbs/v0/kms/<user-name>/<kms-type>/data-key/<cmk-id>
/kbs/v0/kms/<user-name>/<kms-type>/public-key/<cmk-id>
```

Where `user-name` is used to identify the user,
`kms-type` is the type of KMS, such as `Aliyun-KMS`, `Intel-eHSM`, and so on.
`cmk-id` is the unique identifier of the `custom master key (CMK)` in KMS.

Correspondingly, there are two new types of KBS resource URIs (for upstream components such as image-rs and AA):

```
kbs-kms://<kbs-addr>/<user-name>/<kms-type>/data-key/<cmk-id>
kbs-kms://<kbs-addr>/<user-name>/<kms-type>/public-key/<cmk-id>
```

Note that the CMK ID passed in by the API alone is not enough to enable KBS to obtain the correct key from the KMS. The request sent to KMS also needs to contain other information about the key, such as the key length, encrypted data-key itself, and so on. Therefore, we need a mechanism to store the instance information of each key in KBS. Its operation structure is as follows:

![kbs-kms](https://user-images.githubusercontent.com/35883144/223316674-7be92c89-b879-4549-abe4-b47b7781828f.png)

Here is a practical example to illustrate how this mechanism works:

Assuming that KBS receives a request for `/kbs/v0/kms/Alice/aliyun-kms/data-key/8e06-46a1`, KBS first selects Alice's Key Manager proxy according to the `user-name` in the request URL, then selects Aliyun KMS proxy according to the `kms-type` in the request URL, and then selects CMK `8e06-46a1` according to the `cmk-id` in the request URL, Then read the Data-Key-Info (which may contain the key length and the data-key itself encrypted by the CMK private key) and send a request to KMS and obtain the data-key in plain-text.

cc @sameo @jiazhang0

**Comment by Xynnn007** [comment]
Hi @jialez0 

Thanks for the detailed design! The overall design looks great to me. Here are some comments from my side

It seems that the key problem to deal with is how to identify the KMS type. There might be two ways:

#### Way 1

The same way as this proposal shows. A new scheme `kbs-kms://`, which is different from `kbs://`. `kbs-kms://` implies that this resource is from KMS, but a KBS will be directly communicated with to work as a proxy. The scheme `kbs://` would seem a little weird, which means that "this resource is stored inside a KBS, but not in a backend KBS".

- How to use inside guest? For example in policy.json, we can use
```json
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports": {
        "docker": {
            "quay.io/kata-containers/confidential-containers": [
                {
                    "type": "signedBy",
                    "keyPath": "kbs-kms://example.kbs.org/alice/aliyun-kms/public-key/11032d96-dccd-46a3-9244-93644d76745f"
                }
            ]
        }
    }
}
```
- How to impl by KBS? 
We need to open another RESTful API `/kbs/v0/kms/...`. In this way both KBS side and CC-KBC side should handle.

#### Way 2

We extend KBS Resource URI scheme. This means we can add query items in the suffix of a KBS Resource URI. For example `kbs-kms://<kbs-addr>/<user-name>/<kms-type>/data-key/<cmk-id>` will be translated into `kbs://<kbs-addr>/<some-repo>/<some-type>/<some-tag>?kms=<kms-type>&key-type=data-key&key-id=<cmk-id>&...`

- How to use inside guest? For example in policy.json, we can use
```json
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports": {
        "docker": {
            "quay.io/kata-containers/confidential-containers": [
                {
                    "type": "signedBy",
                    "keyPath": "kbs-kms://example.kbs.org/test-repo/test-type/test-tag?kms=aliyun-kms&key-type=public-key&key-id=11032d96-dccd-46a3-9244-93644d76745f&user=alice"
                }
            ]
        }
    }
}
```
- How to impl by KBS? 
We do not need to open any new RESTful API. A conditional judgement logic is needed inside KBS to judge which KMS to be called.

#### Way 3

We agree on some reserved values for `<type>`, and they will be for specific KMS usage. For example:

All `<type>` field prefixed with `kms-datakey-*` should be treated as a signal that this resource should be retrieved from KMS module named `*`, and in datakey way. Similiarly, `kms-publickey-*` refers to a public key from KMS module `*`. `<repository>` is not involved because it is left for potential use for multi-user of a single KBS (We should provide this extensibility). Then, the kid within the KMS could be `<tag>` (in concrete KMS context, this kid refers to CMK id, s.t. customer master key id).

- How to use inside guest? For example in policy.json, we can use
```json
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports": {
        "docker": {
            "quay.io/kata-containers/confidential-containers": [
                {
                    "type": "signedBy",
                    "keyPath": "kbs://example.kbs.org/alice/kms-datakey-aliyun/11032d96-dccd-46a3-9244-93644d76745f"
                }
            ],
            "ghcr.io/confidential-containers": [
                {
                    "type": "signedBy",
                    "keyPath": "kbs://example.kbs.org/alice/image-kek/9244-93644d76745f-11032d96-dccd-46a3"
                }
            ]
        }
    }
}
```
The second key will be fetched directly inside KBS, while the first key will be fetched from KMS via KBS. However all the retrievement operation is transparent to user -- the two requests share a same RESTful API of KBS.
- How to impl by KBS? 
As way 2. We do not need to open any new RESTful API. A conditional judgement logic is needed inside KBS to judge which KMS to be called.

I'm a little agreed on way 3, as what an user can see is only the KBS Resource URI, and the URI format in way 3 looks tidier than way 2. Besides, way 3 could help us to reuse the code inside image-rs and attestation-agent without any modification but way 1 cannot.

However, the shortcoming is obvious - users cannot use any `<type>` name they want, because they must avoid some special values which we need to document.

cc @sameo

**Comment by surajssd** [comment]
I would be interested to integrate Azure Key Vault into KBS to store keys in.

**Comment by surajssd** [comment]
> In the CoCo scenario, two keys need to be obtained from KBS:

IMHO restricting the API upfront to categorize the key into two types is restrictive. There could be other key types like the workload can initiate the attestation using the `getresource` api endpoint of the attestation agent. So partitioning scheme based on predefined key type feels restrictive.

**Comment by Xynnn007** [comment]
@surajssd latest discussion thread https://github.com/confidential-containers/attestation-agent/issues/183

**Comment by fitzthum** [comment]
Seems like this has been taken care of in guest components and the basic KMS drivers for the resource backend. Please re-open if further discussion is needed.
