### ISSUE TITLE
kbs: customize OPA policy when deploy KBS

### ISSUE THREAD

**Issue by huoqifeng** [confidential-containers/trustee#380]
I'd like to customize the OPA policy file which by default located at `/opa/confidential-containers/kbs/policy.rego` and the default value is as below when deploy the service via https://github.com/confidential-containers/trustee/tree/main/kbs/config/kubernetes
```
package policy

default allow = false

allow {
	input["tee"] != "sample"
}
```
Please let me know if it's already supported which I'm not aware yet.

**Comment by fitzthum** [comment]
The kbs [client-tool](https://github.com/confidential-containers/trustee/tree/main/kbs/tools/client) supports updating KBS and AS policies. Will that work for you?

**Comment by huoqifeng** [comment]
Thanks @fitzthum , I'm trying the client via command like this:
```
./kbs-client --url http://192.168.122.180:30579 config --auth-private-key ../../kbs/config/kubernetes/base/kbs.key set-resource-policy --policy-file ../../kbs/sample_policies/allow_all.rego 
```
But got error: `Error: Parse error`
Where the private pem key is generated like here: https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/test/provisioner/provision.go#L134

Checking the help, it mentions only `ED22519` supported.
```
Options:
      --auth-private-key <AUTH_PRIVATE_KEY>
          PEM file path of private key used to authenticate the resource registration endpoint token (JWT) to Key Broker Service. This key can sign legal JWTs. This client tool only support ED22519 key now
```
Checked the client code here: https://github.com/confidential-containers/trustee/blob/main/kbs/tools/client/src/lib.rs#L129
Which seems also `Ed25519KeyPair`, same as what we use.
I'm confused here, is that a typo in help? Any suggestions on what's wrong for me?

**Comment by huoqifeng** [comment]
I'm guessing the private key format is not correct here? https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/test/provisioner/provision.go#L137~L155 , shall we `x509.MarshalPKCS8PrivateKey(privateKey)` before `pem.EncodeToMemory`?

**Comment by huoqifeng** [comment]
Yes, fixed it via correct the private key format, thanks @fitzthum , it works for me, I'm going to close this issue.

**Comment by huoqifeng** [comment]
I'm reopening this issue according to concerns in https://github.com/confidential-containers/cloud-api-adaptor/pull/1824#discussion_r1590578009, maybe there is already a solution on this. The problem is:
- how to use the kbs-client to set policy for multiple replicas deployment? I guess set it pod by pod is not good because the client might not have connection to pod overlay network.

**Comment by huoqifeng** [comment]
@fitzthum any suggestions on question above?

**Comment by Xynnn007** [comment]
For trustee deployment, if we want to update the configs one way is to claim a volume/configmap for `/opa/confidential-containers/kbs/policy.rego` in k8s, thus we can use different policy for different deployments. The OPA working process will do a fresh read upon the policy file for every KBS's api call (resource retrirvement). This hints that we can change the volume/configmap content at runtime, at the same time actually KBSes themselves are stateless.

But for sure, if kbs is deployed with multiple instances without having a common writable storage backend (like volume) and we want to call KBS's api to update policy, we need to call each KBS instance's API to update the same policy for consistance.

**Comment by huoqifeng** [comment]
@Xynnn007 do you mean create a cm and mount it to `/opa/confidential-containers/kbs/policy.rego` in https://github.com/confidential-containers/trustee/blob/main/kbs/config/kubernetes/base/deployment.yaml?

**Comment by Xynnn007** [comment]
> @Xynnn007 do you mean create a cm and mount it to `/opa/confidential-containers/kbs/policy.rego` in https://github.com/confidential-containers/trustee/blob/main/kbs/config/kubernetes/base/deployment.yaml?

right.
