### ISSUE TITLE
How to provide alignment between Trustee and kbs-operator

### ISSUE THREAD

**Issue by lmilleri** [confidential-containers/trustee#381]
The [kbs-operator](https://github.com/confidential-containers/kbs-operator) provides a facilitated method to deploy trustee in a k8s cluster.
The kbs-operator is able to deploy trustee in 2 different ways:
- all-in-one image: all the components in trustee running in a single built-in image
- microservices: one image for each running components (kbs, as, rvps)

In both cases, we have to provide a way to synchronize the operator, making sure it takes the correct images built inside trustee.
I think there are 2 scenarios:
- development: operator can refer to the trustee _staged_ images 
- release: the operator (will be published in the operator hub) can refer to trustee release images

Is my assumption correct?

**Comment by fitzthum** [comment]
That seems reasonable. In this repo the rough idea is that we use Docker compose for development and it points to the latest staged image whereas the kubernetes yaml points to the image from the last release.
