### ISSUE TITLE
Using go instead of rust to implement trustee ?

### ISSUE THREAD

**Issue by fffmonkeyking** [confidential-containers/trustee#393]
Why choose to implement confidential-containers/trustee using the Rust language instead of considering using the Go language to fully implement confidential-containers/trustee ？

**Comment by Xynnn007** [comment]
Hi @fffmonkeyking Trustee are components related to confidential computing, and requires highly security and stability. Rust is claimed to be memory-safe and can efficiently avoid programming bugs like null pointer, also with good performance near to pure C/C++. We followed the rule and have these components implemented as examples.

But for sure, [KBS protocol](https://github.com/confidential-containers/trustee/blob/main/kbs/docs/kbs_attestation_protocol.md) is an open protocol that could be implemented in any language you like.

**Comment by fitzthum** [comment]
The KBS distributes secrets and is usually exposed to the network, so we have to be confident about its security properties. Go does have safeguards, but I think Rust is even stricter with its compiler guarantees.

Also keep in mind that almost every other part of the CoCo project is written in Rust. It's handy to have this kind of coherence.

**Comment by Xynnn007** [comment]
@fffmonkeyking Feel free to reopen this issue.
