### ISSUE TITLE
Add Choi as maintainer

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/trustee#454]
@confidential-containers/kbs-maintainers @confidential-containers/attestation-service-maintainers 

How about adding @BbolroC as a maintainer for this repo?

He's a valued contributor and can help manage the s390x node. As we run more and more jobs, we end up with bottle-necks in our CI nodes. As a maintainer Choi could cancel jobs to help the s390x CI run smoothly.

**Comment by wainersm** [comment]
@BbolroC has been great and giving him superpowers will allow him to debug/fix/dev CI much quicker! so 1+!
