### ISSUE TITLE
KBS Cluster Start-Up documentation is outdated

### ISSUE THREAD

**Issue by AdithyaKrishnan** [confidential-containers/trustee#455]
The documentation for the KBS cluster start up is outdated and needs to be updated with latest docker version steps.

https://github.com/confidential-containers/trustee/blob/a64ccfebf8d4c88430bb28aea38c52ada910dcf0/kbs/docs/cluster.md

**Comment by mkulke** [comment]
Can you describe the exact problem you are running into? This [CI workflow](https://github.com/confidential-containers/trustee/blob/main/.github/workflows/kbs-docker-e2e.yml) is using the docker-compose manifest

**Comment by fitzthum** [comment]
I guess someone should update `docker-compose up -d` to `docker compose up -d` in that doc.
