### ISSUE TITLE
Missing plugin 'Resource'

### ISSUE THREAD

**Issue by litian1992** [confidential-containers/trustee#570]
### Describe the bug

[[plugins]] section is missing in kbs/config/kbs-config.toml
And so this error occurs upon get/set resources:
[2024-11-11T06:18:13Z ERROR kbs::error] PluginNotFound { plugin_name: "resource" }

### How to reproduce

/usr/local/bin/kbs --config-file config/kbs-config.toml &
/usr/local/bin/kbs-client --url http://127.0.0.1:8080 get-resource --path default/test/dummy

### CoCo version information

latest

### What TEE are you seeing the problem on

AzSnpVtpm

**Comment by Xynnn007** [comment]
@litian1992 Thanks for the bug report. I put a fix PR please take a look if convenient for you : )

**Comment by litian1992** [comment]
@Xynnn007 LGTM. Appreciate the quick response.
