### ISSUE TITLE
Retrieving a resource with name with extension throws error

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/trustee#593]
### Describe the bug

Retrieving a resource with name having the pattern <name>.<ext> fails with the following error
"[2024-11-24T12:59:21Z ERROR kbs::error] PluginInternalError { source: illegal ResourceDesc format. }"

### How to reproduce

Create a secret `key.pub` or `key.txt` under `/opt/confidential-containers/kbs/repository/default/secret/` and retrieve it using CDH.

```
curl http://127.0.0.1:8006/cdh/resource/default/secret/key.txt

rpc status: Status { code: INTERNAL, message: "[CDH] [ERROR]: Get Resource failed", details: [], special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
```

Following error is thrown on the Trustee KBS side
```
"[2024-11-24T12:59:21Z ERROR kbs::error] PluginInternalError { source: illegal ResourceDesc format. }"
```

### CoCo version information

main

### What TEE are you seeing the problem on

Snp

**Comment by Xynnn007** [comment]
oh. Now we have a regex that only allows number, alphabet, - and _
